
try{
    let result  = num1+ num2
    console.log(result);
}
catch(err){
    console.log(err.message);
}

console.log("after res.send");
    